### ISSUE TITLE
Instantaneous crash

### ISSUE THREAD

**Issue by Nexusbeeyst** [EasyRPG/Player#1004]
I'm using an samsung galaxy tab 3, opening the game causes it to stop working, the app store version is no exception, there is no log file or anything, it just won't run.

**Comment by Ghabry** [comment]
Do you know logcat?

**Comment by Nexusbeeyst** [comment]
I reported it

**Comment by Ghabry** [comment]
Thanks we received it.

CC @BlisterB 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.easyrpg.player/org.easyrpg.player.game_browser.GameBrowserActivityAPI15}: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.design.widget.NavigationView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2250)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2304)
	at android.app.ActivityThread.access$700(ActivityThread.java:152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.design.widget.NavigationView
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at org.easyrpg.player.game_browser.GameBrowserActivityAPI15.onCreate(GameBrowserActivityAPI15.java:47)
	at android.app.Activity.performCreate(Activity.java:5345)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:593)
	... 22 more
Caused by: java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenu
	at android.support.design.widget.NavigationView.<init>(NavigationView.java:104)
	at android.support.design.widget.NavigationView.<init>(NavigationView.java:95)
	... 25 more
```

**Comment by Nexusbeeyst** [comment]
Is there any solution?

**Comment by BlisterB** [comment]
Hi everyone :). 
NoClassDefFoundError is a really strange problem.
@Nexusbeeyst , can you provide some information about your tablet : what is it's android version? More important, are you using a custom ROM?

(I've got a big college thing on fire, I'll won't be able to bend on this crash until Friday.)

**Comment by Nexusbeeyst** [comment]
I am not running a custom rom, my android version is 4.2.2.

**Comment by fdelapena** [comment]
Maybe is a bug in the support library which is fixed in version 24: https://code.google.com/p/android/issues/detail?id=187255

**Comment by BlisterB** [comment]
Yep @fdelapena it seems to be that.
There is a fix using ProGuard which I really don't like, I will upgrade to this API Friday unless someone want to do that before :).

**Comment by BlisterB** [comment]
@Nexusbeeyst this problem will be resolved in few days, it will come with some cools things about the android port :). Sorry for the Google/Samsung bug :p.

**Comment by Ghabry** [comment]
I guess the line is: app/build.gradle:31:    compile 'com.android.support:appcompat-v7:23.4.0'

**Comment by BlisterB** [comment]
Yep, this is really quick to fix (we will probably also have to switch targetSdk to 24), but it needs some tests to be sure everything works on few devices (because you know, Android).

**Comment by Nexusbeeyst** [comment]
Thanks

**Comment by Ghabry** [comment]
@Nexusbeeyst 
The new release should fix the crash. Please wait a few hours for google play to update the version.

Or use the one on https://ci.easyrpg.org/job/player-android/

Please tell us if the crash is resolved.

**Comment by Nexusbeeyst** [comment]
It's fixed, thanks.

**Comment by Ghabry** [comment]
Thanks for the report

**Comment by BlisterB** [comment]
Yay
