### ISSUE TITLE
[Android] Crash related to game folder

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#1021]
From Ghabry:

Crash reported on Android

```
java.lang.NullPointerException
    at org.easyrpg.player.settings.SettingsManager.setGameFolderList(SettingsManager.java:120)
    at org.easyrpg.player.settings.SettingsManager.addGameDirectory(SettingsManager.java:105)
    at org.easyrpg.player.settings.SettingsGamesFoldersActivity$2.run(SettingsGamesFoldersActivity.java:84)
    at org.easyrpg.player.DirectoryChooser$1$1.onClick(DirectoryChooser.java:67)
    at android.view.View.performClick(View.java:4204)
    at android.view.View$PerformClick.run(View.java:17393)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5117)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:954)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:721)
    at dalvik.system.NativeStart.main(Native Method)
```

I had this also once. Happens when the game directory list is empty. No idea how this happens, usually restarting the app fixed it shrug

**Comment by Ghabry** [comment]
Another one is this here but no idea how this is supposed to happen:

```
java.lang.NullPointerException
	at org.easyrpg.player.settings.SettingsManager.setAudioEnabled(SettingsManager.java:158)
	at org.easyrpg.player.settings.SettingsAudioActivity.onClick(SettingsAudioActivity.java:30)
	at android.view.View.performClick(View.java:4212)
	at android.widget.CompoundButton.performClick(CompoundButton.java:100)
	at android.view.View$PerformClick.run(View.java:17476)
	at android.os.Handler.handleCallback(Handler.java:800)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
```

Everybody using Xposed Framework :D

**Comment by Ghabry** [comment]
@BlisterB How is the French translation progressing :smile:

**Comment by BlisterB** [comment]
Hello Ghabry, I currently have a lot of important things on fire. Don't hesitate to assign me issues on Github, I'll deal with them as soon as possible.

**Comment by Ghabry** [comment]
Looks like the reason for this is Androids smart memory manager which terminates background activities. The settings are deleted (because they are only created once on startup) and we have to reinit them in any activity that want to use them m(
