### ISSUE TITLE
Android 7.0: FileUriExposedException after selecting "Report Bug"

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1105]
Google continues wasting developer time by randomly breaking APIs. Android 7.0 market share is currently 2% and will become more soon :-1:. Fortunately this only breaks the "Report Bug" function. (which is quite ironic).

Stacktrace:
```
android.os.FileUriExposedException: file:///storage/emulated/0/easyrpg/rtp/2000/nobita_hazard/easyrpg_log.txt exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
	at android.app.Activity.startActivityForResult(Activity.java:4224)
	at android.app.Activity.startActivityForResult(Activity.java:4183)
	at android.app.Activity.startActivity(Activity.java:4507)
	at android.app.Activity.startActivity(Activity.java:4475)
	at org.easyrpg.player.player.EasyRpgPlayerActivity$3.onClick(EasyRpgPlayerActivity.java:239)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:164)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Proposed solution on stackoverflow: https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

Relevant Code for reference:
```java
ArrayList<Uri> files = new ArrayList<Uri>();
String savepath = getIntent().getStringExtra(TAG_SAVE_PATH);
files.add(Uri.fromFile(new File(savepath + "/easyrpg_log.txt"))); // Uri.fromFile -> BAD
for (File f : GameBrowserHelper.getSavegames(new File(savepath))) {
	files.add(Uri.fromFile(f));  // Uri.fromFile -> BAD
}

Intent intent = new Intent(Intent.ACTION_SEND_MULTIPLE);
intent.setData(Uri.parse("mailto:"));
intent.setType("*/*");
intent.putExtra(Intent.EXTRA_EMAIL, new String[]{"easyrpg@easyrpg.org"});
intent.putExtra(Intent.EXTRA_SUBJECT, "Bug report");
intent.putExtra(Intent.EXTRA_TEXT, getApplicationContext().getString(R.string.report_bug_mail));
intent.putExtra(Intent.EXTRA_STREAM, files);
if (intent.resolveActivity(getPackageManager()) != null) {
	startActivity(intent); // CRASH
}
```

CC @BlisterB

**Comment by Ghabry** [comment]
The message provided by the user to the crsh is "武器が装備できませんどうゆう事ですか" which translates to "I can not equip you with weapons. What do you mean?" ¯\\\_(ツ)_/¯

**Comment by BlisterB** [comment]
Hi Ghabry :).

Eeeeerf Android.
An easy fix is to lower the the targetVersionSdk version to 23, I currently don't have an Android 7.0 device and I'm afraid to encounter similar issues without extensive tests. Of course we can still apply your tip later and test it with compatible devices. Are you ok with this solution?
