### ISSUE TITLE
Memory leaks in filefinder code

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2437]
These 2 places have a memory leak:

https://github.com/EasyRPG/Player/blob/master/src/filefinder.cpp#L666
https://github.com/EasyRPG/Player/blob/master/src/filefinder.cpp#L682

Probably the stream needs to take ownership of and store the filebuf

**Comment by Ghabry** [comment]
Did you make a leak check to verify this?

According to the documentation of ``open``:

> The function returns this if successful.

Which means it is destroyed later via ``delete rdbuf();`` in the Input/OutputStream class.

**Comment by fmatthew5876** [comment]
> Did you make a leak check to verify this?

I discovered this via address sanitizer

```
Debug: EasyRPG Player 0.6.2 started
Debug: ============================
Debug: Clock: StdSteady steady=true period=ns (1 / 1000000000)
Debug: Seeded the RNG with 1610372897.
Debug: CLI: --window --test-play --disable-audio --project-path /mnt/c/Users/matt/Documents/RPG Maker 2003/DynGame/ 
Debug: SDL2: RendererInfo hw=true sw=false vsync=false
Debug: SDL2: Detected format (0) SDL_PIXELFORMAT_ARGB8888 : rank=(2)
Debug: SDL2: Detected format (1) SDL_PIXELFORMAT_ABGR8888 : rank=(2)
Debug: SDL2: Selected Pixel Format SDL_PIXELFORMAT_ARGB8888
Debug: Detected encoding: UTF-8
Debug: Using /mnt/c/Users/matt/Documents/RPG Maker 2003/DynGame/ as Game and Save directory
Debug: Loading game Untitled
Debug: Using RPG2k3 Interpreter
Debug: RPG2k >= v1.50 / RPG2k3 >= v1.05 detected
Debug: Engine configured as: 2k=false 2k3=true MajorUpdated=true Eng=false
Debug: wine prefix not found: "/home/matt/.wine"
Debug: wine prefix not found: "/home/matt/.wine"
Debug: wine prefix not found: "/home/matt/.wine"
Debug: wine prefix not found: "/home/matt/.wine"
Debug: wine prefix not found: "/home/matt/.wine"
Debug: wine prefix not found: "/home/matt/.wine"
Warning: This game uses DynRPG and will not run properly.
Debug: Patch configuration: dynrpg=true maniac=false
Debug: Cannot find: ./ExFont
Debug: Loading ExFont from /mnt/c/Users/matt/Documents/RPG Maker 2003/DynGame//RPG_RT.exe
Debug: EXEReader: EXFONT resource found (DE 0xde2a0; 0xe1718; len 0x2168)
Debug: Actor 1: Removing item 44 from equipment slot 2 (Not equippable by this actor)
Debug: Actor 1: Removing item 67 from equipment slot 4 (Not equippable by this actor)
Debug: libpng: iCCP: known incorrect sRGB profile
Debug: libpng: cHRM: inconsistent chromaticities
Debug: Actor 1: Removing item 44 from equipment slot 2 (Not equippable by this actor)
Debug: Actor 1: Removing item 67 from equipment slot 4 (Not equippable by this actor)

=================================================================
==13772==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x7fcf930bf947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7fcf9830f1bb in FileFinder::OpenInputStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode) /mnt/c/Users/matt/Documents/dev/Player/src/filefinder.cpp:666
    #2 0x7fcf984e7d62 in Game_Ineluki::ExecuteScriptList(nonstd::sv_lite::basic_string_view<char, std::char_traits<char> >) /mnt/c/Users/matt/Documents/dev/Player/src/game_ineluki.cpp:210
    #3 0x7fcf97af4df1 in Player::CreateGameObjects() /mnt/c/Users/matt/Documents/dev/Player/src/player.cpp:816
    #4 0x7fcf97d91c65 in Scene_Logo::Update() /mnt/c/Users/matt/Documents/dev/Player/src/scene_logo.cpp:72
    #5 0x7fcf97aef109 in Player::Update(bool) /mnt/c/Users/matt/Documents/dev/Player/src/player.cpp:379
    #6 0x7fcf97d3e57b in Scene::MainFunction() /mnt/c/Users/matt/Documents/dev/Player/src/scene.cpp:185
    #7 0x7fcf97aed38c in Player::MainLoop() /mnt/c/Users/matt/Documents/dev/Player/src/player.cpp:254
    #8 0x7fcf97aecfe8 in Player::Run() /mnt/c/Users/matt/Documents/dev/Player/src/player.cpp:234
    #9 0x7fcf97aeb9b1 in main /mnt/c/Users/matt/Documents/dev/Player/src/main.cpp:28
    #10 0x7fcf911870b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7fcf930bdbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fcf90eeb5a6 in _XlcDefaultMapModifiers (/lib/x86_64-linux-gnu/libX11.so.6+0x5b5a6)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fcf930bddc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7fcf80466095  (/mnt/c/Users/matt/Documents/dev/Player/bldcli/easyrpg-player+0x11994095)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fcf930bddc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7fcf8046607e  (/mnt/c/Users/matt/Documents/dev/Player/bldcli/easyrpg-player+0x1199407e)

SUMMARY: AddressSanitizer: 353 byte(s) leaked in 4 allocation(s).
```

From just starting player and choosing Quit from the title screen
