### ISSUE TITLE
Player crashes on startup since #445 merge

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#447]
After trying to run some games. Player built with g++ 4.9.

```gdb
0x000000000044657e in std::vector<short, std::allocator<short> >::~vector (this=0xb0, __in_chrg=<optimized out>) at /usr/include/c++/4.9.2/bits/stl_vector.h:425
425			      _M_get_Tp_allocator()); }
#0  0x000000000044657e in std::vector<short, std::allocator<short> >::~vector (this=0xb0, __in_chrg=<optimized out>) at /usr/include/c++/4.9.2/bits/stl_vector.h:425
#1  0x000000000044e70b in RPG::SaveActor::~SaveActor (this=0x0, __in_chrg=<optimized out>) at /usr/include/liblcf/rpg_saveactor.h:21
#2  0x000000000044e83f in std::_Destroy<RPG::SaveActor> (__pointer=0x0) at /usr/include/c++/4.9.2/bits/stl_construct.h:93
#3  0x000000000044c321 in std::_Destroy_aux<false>::__destroy<RPG::SaveActor*> (__first=0x0, __last=0xffffffff) at /usr/include/c++/4.9.2/bits/stl_construct.h:103
#4  0x000000000044a347 in std::_Destroy<RPG::SaveActor*> (__first=0x0, __last=0xffffffff) at /usr/include/c++/4.9.2/bits/stl_construct.h:126
#5  0x000000000044760f in std::_Destroy<RPG::SaveActor*, RPG::SaveActor> (__first=0x0, __last=0xffffffff) at /usr/include/c++/4.9.2/bits/stl_construct.h:151
#6  0x00007ffff7990bc2 in std::vector<RPG::SaveActor, std::allocator<RPG::SaveActor> >::_M_erase_at_end (this=0x8632b0 <Main_Data::game_data+1968>, __pos=0x0) at /usr/include/c++/4.9.2/bits/stl_vector.h:1438
#7  0x00007ffff7a6ea5c in std::vector<RPG::SaveActor, std::allocator<RPG::SaveActor> >::clear (this=0x8632b0 <Main_Data::game_data+1968>) at /usr/include/c++/4.9.2/bits/stl_vector.h:1212
#8  0x00007ffff7a6e5e2 in RPG::Save::Setup (this=0x862b00 <Main_Data::game_data>) at src/rpg_setup.cpp:160
#9  0x000000000043e4cb in Player::CreateGameObjects () at src/player.cpp:476
        init = true
#10 0x00000000004561fe in Scene_Logo::Update (this=0x28a6300) at src/scene_logo.cpp:925
#11 0x000000000043d0ee in Player::Update (update_scene=true) at src/player.cpp:246
        framerate_interval = 16.666666666666668
        cur_time = 470
#12 0x00000000004549a3 in Scene::MainFunction (this=0x28a6300) at src/scene.cpp:95
        init = true
        __PRETTY_FUNCTION__ = "virtual void Scene::MainFunction()"
#13 0x000000000043cd82 in Player::MainLoop () at src/player.cpp:174
#14 0x000000000043ccd8 in Player::Run () at src/player.cpp:169
#15 0x0000000000432f95 in main (argc=2, argv=0x7fffffffdfa8) at src/platform/sdl_main.cpp:31
```

**Comment by Ghabry** [comment]
Was this compiled against the latest version of liblcf?

Can't think of a way to crash with my graphics code in RPG-classes.

**Comment by Ghabry** [comment]
Works for me.

![unbenannt](https://cloud.githubusercontent.com/assets/1331889/6865341/1178fb20-d46d-11e4-808b-80b635de3827.PNG)

**Comment by fdelapena** [comment]
After rebuilding everything on another machine works fine, sorry for the noise.
