### ISSUE TITLE
Battle: sporadic crash after defeat vs particular battle group in Off game

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#563]
In Off (translation 2.0) there is a battle where there is a group with big attacks, they sum more than 999HP. ~~where the defeat should continue and don't trigger a Game Over. Also,~~ Player sometimes crashes. ~~If you don't set start party you can see the correct battle defeat without game over~~:

    easyrpg-player --start-map-id 353 --start-party 12

My backtrace:

```dtrace
Program received signal SIGSEGV, Segmentation fault.
0x0000000000551692 in Game_BattleAlgorithm::Skill::Execute (this=0x2cc4990)
    at src/game_battlealgorithm.cpp:536
536						(*current_target)->GetDef() * skill.magical_rate / 40;

#0  0x0000000000551692 in Game_BattleAlgorithm::Skill::Execute (this=0x2cc4990)
    at src/game_battlealgorithm.cpp:536
        effect = 0
        __PRETTY_FUNCTION__ = "virtual bool Game_BattleAlgorithm::Skill::Execute()"
#1  0x0000000000538138 in Scene_Battle_Rpg2k3::ProcessBattleAction (this=0x2c7ebf0, action=0x2cc4990)
    at src/scene_battle_rpg2k3.cpp:470
        source_sprite = 0x2e8fb40
#2  0x0000000000537c8a in Scene_Battle_Rpg2k3::ProcessActions (this=0x2c7ebf0)
    at src/scene_battle_rpg2k3.cpp:387
No locals.
#3  0x0000000000527787 in Scene_Battle::Update (this=0x2c7ebf0) at src/scene_battle.cpp:167
        timer1 = 2050
        timer2 = 0
        events_finished = true
#4  0x00000000005365f6 in Scene_Battle_Rpg2k3::Update (this=0x2c7ebf0)
    at src/scene_battle_rpg2k3.cpp:89
No locals.
#5  0x000000000043df51 in Player::Update (update_scene=true) at src/player.cpp:250
        framerate_interval = 16,666666666666668
        cur_time = 181838
#6  0x00000000004562ce in Scene::MainFunction (this=0x2c7ebf0) at src/scene.cpp:96
        init = true
        __PRETTY_FUNCTION__ = "virtual void Scene::MainFunction()"
#7  0x000000000043dc53 in Player::MainLoop () at src/player.cpp:178
No locals.
#8  0x000000000043dbdc in Player::Run () at src/player.cpp:173
No locals.
#9  0x0000000000431f15 in main (argc=2, argv=0x7fffffffdf88) at src/platform/sdl_main.cpp:31
No locals.

```

**Comment by Ghabry** [comment]
Was that the non-scripted battle which only needs 9999 HP limit?

**Comment by fdelapena** [comment]
Yes, this battle required 4-digit HP to survive the attack. At leas the gameover issue is solved. I'll check later but maybe the low HP value was related with the crash.

**Comment by fdelapena** [comment]
Now with 9999HP the critical issue is fixed for OFF. :+1:
It is hard to crash now. A possible hint for this is: random "purification messages" appear on defeat. Maybe it crashes when the count is 0.

**Comment by Ghabry** [comment]
Probably already fixed by the battle animation crashfix... reopen if you encounter this again
