### ISSUE TITLE
Embric of Wulfhammer's Castle: PC orders in battle not loaded correctly

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#601]
In this game, in combat the PC orders (not sure if that's the correct term. Attack/defend/item and the like.) don't seem to be loaded at all. In their place you are presented with an empty list of options, and pressing enter instantly crashes the game.

Steps to reproduce: 
* Download game (portable version of the Deluxe edition) from http://aeresland.net/ 
* Download my savegame from http://www.heavylobster.com/files/Save03.lsd 
* Take one step north to enter battle
* Select "Strategize"

Screenshot of correct behavior using RPG_RT.exe: http://www.heavylobster.com/pics/embric_working.png
Screenshot of broken behavior using easyRPG: http://www.heavylobster.com/pics/embric_broken.png

**Comment by fdelapena** [comment]
Crash stack trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000537731 in Scene_Battle_Rpg2k3::CommandSelected (this=0x452cab0)
    at src/scene_battle_rpg2k3.cpp:722
722		active_actor->SetLastBattleAction(command.ID);
#0  0x0000000000537731 in Scene_Battle_Rpg2k3::CommandSelected (this=0x452cab0)
    at src/scene_battle_rpg2k3.cpp:722
        command = @0x1802e16a90: <error reading variable>
#1  0x00000000005374b9 in Scene_Battle_Rpg2k3::ProcessInput (this=0x452cab0)
    at src/scene_battle_rpg2k3.cpp:638
No locals.
#2  0x00000000005260f4 in Scene_Battle::Update (this=0x452cab0)
    at src/scene_battle.cpp:175
        timer1 = 0
        timer2 = 0
        events_finished = true
#3  0x0000000000534d89 in Scene_Battle_Rpg2k3::Update (this=0x452cab0)
    at src/scene_battle_rpg2k3.cpp:90
No locals.
#4  0x000000000043dd4f in Player::Update (update_scene=true)
    at src/player.cpp:253
        framerate_interval = 16,666666666666668
        cur_time = 23002
#5  0x0000000000455856 in Scene::MainFunction (this=0x452cab0)
    at src/scene.cpp:96
        init = true
        __PRETTY_FUNCTION__ = "virtual void Scene::MainFunction()"
#6  0x000000000043da51 in Player::MainLoop () at src/player.cpp:181
No locals.
#7  0x000000000043d9da in Player::Run () at src/player.cpp:176
No locals.
#8  0x0000000000431ce5 in main (argc=2, argv=0x7fffffffe038)
    at src/platform/sdl_main.cpp:31
No locals.
```
