### ISSUE TITLE
Battle: segfault in OFF when fighting with an enemy group with spawning enemies

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#723]
There is an enemy when sometimes appears a part which was invisible, and after some attack turn (is an animation targetting it?), it crashes. The pattern looks like the enemy disappears then appears the 2nd time and when this skill is repeated, crashes. Reported by [fraekugel](https://twitter.com/fraekugel/status/685466473796616192). Backtrace:

```dtrace
Program received signal SIGSEGV, Segmentation fault.
0x0000000000557793 in Scene_Battle_Rpg2k3::ProcessActions (this=0x28a3fa0) at src/scene_battle_rpg2k3.cpp:463
463				Game_Enemy* target = static_cast<Game_Enemy*>(enemies[target_window->GetIndex()]);
(gdb) bt f
#0  0x0000000000557793 in Scene_Battle_Rpg2k3::ProcessActions (this=0x28a3fa0) at src/scene_battle_rpg2k3.cpp:463
        enemies = std::vector of length 0, capacity 0
        target = 0x255bb70
        sprite = 0x27c8a50
#1  0x000000000053ccbc in Scene_Battle::Update (this=0x28a3fa0) at src/scene_battle.cpp:168
        timer1 = 1531
        timer2 = 0
        events_finished = true
#2  0x0000000000555add in Scene_Battle_Rpg2k3::Update (this=0x28a3fa0) at src/scene_battle_rpg2k3.cpp:90
No locals.
#3  0x000000000043b306 in Player::Update (update_scene=true) at src/player.cpp:263
        framerate_interval = 16,666666666666668
        cur_time = 166258
#4  0x0000000000454fc0 in Scene::MainFunction (this=0x28a3fa0) at src/scene.cpp:98
        init = true
        __PRETTY_FUNCTION__ = "virtual void Scene::MainFunction()"
#5  0x000000000043b004 in Player::MainLoop () at src/player.cpp:189
No locals.
#6  0x000000000043af8d in Player::Run () at src/player.cpp:184
No locals.
#7  0x000000000042f775 in main (argc=3, argv=0x7fffffffe058) at src/main.cpp:32
No locals.
```

[Savegame](https://fran.cr/owncloud/index.php/s/EYJ2FimTIQ9jqoF/download). Open the door and the battle will start.

**Comment by Ghabry** [comment]
Looks like one of the typical stack traces reported via Google Play. But they are useless because I can't add metadata like the game Name to them.
Thx for this one ^^
